package com.brios.miempresa.core.ui.theme

import androidx.compose.ui.graphics.Color

// M3 Light Scheme (generated from primary #F18824)
val primaryLight = Color(0xFFF18824)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFDCC4)
val onPrimaryContainerLight = Color(0xFF6C3A08)
val secondaryLight = Color(0xFF745944)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFDCC4)
val onSecondaryContainerLight = Color(0xFF5B412F)
val tertiaryLight = Color(0xFF00687B)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFAEECFF)
val onTertiaryContainerLight = Color(0xFF004E5D)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFFF8F5)
val onBackgroundLight = Color(0xFF221A14)
val surfaceLight = Color(0xFFFFF8F5)
val onSurfaceLight = Color(0xFF221A14)
val surfaceVariantLight = Color(0xFFF3DFD2)
val onSurfaceVariantLight = Color(0xFF51443B)
val outlineLight = Color(0xFF84746A)
val outlineVariantLight = Color(0xFFD6C3B7)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF382F28)
val inverseOnSurfaceLight = Color(0xFFFEEEE4)
val inversePrimaryLight = Color(0xFFFFB780)
val surfaceDimLight = Color(0xFFE7D7CE)
val surfaceBrightLight = Color(0xFFFFF8F5)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF1E9)
val surfaceContainerLight = Color(0xFFFBEBE1)
val surfaceContainerHighLight = Color(0xFFF5E5DC)
val surfaceContainerHighestLight = Color(0xFFEFDFD6)

// Semantic colors (custom, not part of M3 scheme)
val SuccessGreen = Color(0xFF10B981)
val WarningAmber = Color(0xFFFFC300)
val WhatsAppGreen = Color(0xFF25D366)
val OfflineBannerYellow = Color(0xFFFFF3CD)
val OnOfflineBannerYellow = Color(0xFF856404)
val PlaceholderBG = Color(0xFF919191)
val OnPlaceholderBG = Color(0xFF575757)
